"""empty message

Revision ID: 25e963323057
Revises: 
Create Date: 2018-07-18 22:02:03.865963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25e963323057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_sn', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=80), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=False),
    sa.Column('telephone', sa.String(length=16), nullable=False),
    sa.Column('fax', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('provider_name'),
    sa.UniqueConstraint('provider_sn')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_sn', sa.String(length=32), nullable=False),
    sa.Column('product', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('numbers', sa.Float(precision=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_sn')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_sn', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('telephone', sa.String(length=16), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_sn'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('bills')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('providers')
    # ### end Alembic commands ###
